name: food_delivery_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.2
  flutter_slidable: ^2.0.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  logger: ^1.2.2
  dio: ^5.0.1
  skeletons: ^0.0.3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/image/
    - assets/icon/

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          style: italic

    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          style: italic


